sudo: false
cache:
  directories:
  - $HOME/.gradle
language: groovy
jdk:
- oraclejdk7
before_script:
- rm -rf target
- chmod +x travis-build.sh
script: ./travis-build.sh
env:
  global:
  - GIT_NAME="Soeren Berg Glasius"
  - GIT_EMAIL="soeren@glasius.dk"
  - secure: r5yVKHdZcRo+6vqkukubc9W0ot86DGvAvx/Zlx3wBCjdtvshFYfrTKKTdeXlUSNtdZSaNMgBPw2s4/ZgDxiZunhu4SZCxu/6pi3gP8oYsGjHDuf4Ur+fDaHk8F5CzrDcgwoNApgX9YX4tWfuzDmCMCG/F5ORxTsKOijIzdnW/J9RqqmXSwSgiNRW6sg++g75/+AiLYIkTaAzLYgDpfibcLb+SZ4Dc36lX7zN/NR+qQqnq4xUktxqTa0i33jRe3kaho07z/Lvia3l7tcNzl7hqwj/MRJJ40xkVAqPv8ZshY6DdjcInjs0JnZABqAMCpHb2Sk+JjFccWAnhMek/WVH2ibHt1T7s7GWXCOI1mKSxp7E3L2famW2IgNwsBCyU6emZbXjBwk3daS/PppY4AOjG7DfS5UaAkIkRHua854TqV3+vT1ryi9XDfUh3uOTLFhrgAilFCBnnpyjhnAZKkz75CiHXldTX8D/CqKvu6IGUhqGiI+8MEgV+uG8f3/uUnylvN7Z2E9VhOBqF5h8JsO4LtT+P8LpEt+wzhAMkOsowsDysNcHSxEdznbhIIgTgfFfJ8V08mWhZoNhuqWlwC7FKCP3gKW14Yxmj0AGSxZL/BdU/O49ze1g3Gf9akklDPzUfMd43cTZ9SzgmKNtKH6N0a92v2yC6qT5WMe6bT9T3J0=
  - secure: HpuIBTrqw7hBmuTUXHuDPUU7sHsgNOOR2XQ9nrynHODzMPza7Lklgsd0xuWpe9gkhQ4pj6EWyDbHXJaJCR++MsTlyl8p2vJDk0Z4RbjcnwB5IIXCsHAa2lVOGyqG61xnAC6148ZqQZmlnUblIPXYh7azNKyG+WIltLQuH55y664xOcvgfq1utGaceYb40JN1FTQmObhHLnpS4w0foB2gQSgMpsoMcndCsM9l7gQy1JHEZ7fSMCjtBV9oLLmCjqGr81u1oWaQko+ltzBkxrjB5pgaGkJjaIifOqSur3qIOp4gKDRljfRBJ/aMl/wvYtIT7G2rGXL7YnSSYFUuoFtsZb9r7cID9eFcZvUj/34YIOuQzskzwJYRzv1ZRinwCnh3hGL0glUV7gPxTvQWDjTdw4/OGB3Lj8/NTM48F9skltg6co139pl4lPeT9XOZ/F7CnOi24tm2VE3pc0EceOvWuHnZPnmmu3o2UbAyfPNk4SNJ5hQBgj0w2EMCibwnwhBCc6Rbe7MOUyA4CSTlH7QRWuPG0tg/NPSXvxwHh64Ol0jtJiiE5qqgR4hbZkxQhR6oLBoXYI0fuj0xCC9yI9jt+wwOuorNI55kjLGwrI61acRBqNgljiMA3DYnk7GqK7MFDMm6/sVxRZtcPbUdMsS/zqwH7CBQiAT6l51j5uArHNY=
